<script type="text/javascript">
    $(document).ready(function () {
        $('#tableContainer').jtable({
            title: 'History',
            actions: {
                listAction: '/api/history/list'
            },
            fields: {
                id: {
                    key: true,
                    list: false
                },
                status: {
                    title: 'Status',
                    width: '25%',
                },
                datetime: {
                    title: 'Date',
                    width: '45%',
                }
                temp: {
                    title: 'Temp',
                    width: '15%',
                }
                node: {
                    title: 'Node',
                    width: '15%',
                }
            }
        });

        $('#tableContainer').jtable('load');
    });
</script>

<div id="tableContainer"></div>
