<script type="text/javascript">
    $(document).ready(function () {
        $('#tableContainer').jtable({
            title: 'Historyoverride',
            actions: {
                listAction: '/api/historyoverride/list'
            },
            fields: {
                id: {
                    key: true,
                    list: false
                },
                date: {
                    title: 'Date',
                    width: '55%',
                },
                heatingTemp: {
                    title: 'Temp',
                    width: '15%',
                },
                duration: {
                    title: 'Duration',
                    width: '15%',
                },
                enabled: {
                    title: 'Enabled',
                    width: '15%',
                }
            }
        });

        $('#tableContainer').jtable('load');
    });
</script>


<div id="tableContainer"></div>
