<?php echo $this->partial('partials/time.phtml'); ?>

<?php $this->headScript()->appendFile('/js/jquery-ui-timepicker-addon.js');?>

<?php
$filename = "/var/log/connectivity.txt";
$handle = fopen($filename, "r");
$contents = fread($handle, filesize($filename));
fclose($handle);

echo nl2br($contents);

echo "</br>";

$filename = "/var/log/boiler_scheduler.txt";
$handle = fopen($filename, "r");
$contents = fread($handle, filesize($filename));
fclose($handle);

echo nl2br($contents);

echo "</br>";

$filename = "/var/log/system_check.txt";
$handle = fopen($filename, "r");
$contents = fread($handle, filesize($filename));
fclose($handle);

echo nl2br($contents);

$filename = "http://192.168.1.70/system-check.txt";
$news = fopen($filename, "r"); // or die ("Link does not exist!");
unset($text);
while (!feof($news)) {
  $newbuffer = fgets($news, 4096);
  $text[] = $newbuffer;
};
fclose($news);
$text = implode(" ", $text);

echo nl2br($text);