<?php echo $this->partial('partials/time.phtml'); ?>

<?php $this->headScript()->appendFile('/js/jquery-ui-timepicker-addon.js');?>

<?php
$filename = "/tmp/boiler_scheduler.txt";
$handle = fopen($filename, "r");
$contents = fread($handle, filesize($filename));
fclose($handle);

echo nl2br($contents);

$filename = "/var/log/connectivity.txt";
$handle = fopen($filename, "r");
$contents = fread($handle, filesize($filename));
fclose($handle);

echo nl2br($contents);