#!/bin/sh
# Measure temp via sudo .... /opt/vc/bin/vcgencmd measure_temp 
# root@raspberrypi:/home/pi# /opt/vc/bin/vcgencmd measure_temp
# temp=44.4'C
# wiki.stocksy.co.uk/wiki/Raspberry_Pi_onboard_temperature_sensors

echo "Updated $(date)"
echo "Checking internet connectivity..."
ping -c 5 192.168.1.70>>/dev/null

if [ $? -eq  0 ]
then
    echo "Connected to 192.168.1.70 successfully."
    echo 0 > /var/www/boiler-scheduler/cronjob/control2drayton.txt
else
    echo "Connection to 192.168.1.70 failed."
    #/usr/bin/php /var/www/boiler-scheduler/cronjob/control2drayton.php
    echo 1 > /var/www/boiler-scheduler/cronjob/control2drayton.txt
fi

