#!/bin/sh
# Demonstrated for fun by guys at ihaveapc.com
# Ping a standard website with output suppressed, if ping completes then display success else failure

echo "Checking internet connectivity..."
ping -c 5 192.168.1.70>>/dev/null

if [ $? -eq  0 ]
then
    echo "Connected to 192.168.1.70 successfully."
    echo 0 > /var/www/boiler-scheduler/cronjob/control2drayton.txt
else
    echo "Connection to 192.168.1.70 failed."
    /usr/bin/php /var/www/boiler-scheduler/cronjob/control2drayton.php
    echo 1 > /var/www/boiler-scheduler/cronjob/control2drayton.txt
fi

