<div class="boost_table">
    <table>
        <tr>
            <td>Time:</td>

            <td><span id="clock"></span></td>
        </tr>
        <!--
        <tr>
            <td>Hot Water:</td>
            <td><img id="water" src="/images/circle_red.png" /></td>
            <td class="small">Boost:</td>
            <td class="small"><img id="waterBoost" src="/images/off.png" /><br/>
                <span id="waterBoostTime"></span></td>
        </tr>
        -->

        <tr>
            <td>Heating:</td>
            <!--    <td><img id="heating" src="/images/circle_red.png" /></td> -->

            <td class="small">Boost:</td>

            <td class="small"><img id="heatingBoost" src="/images/off.png"><br>
                <span id="heatingBoostTime"></span></td>
        </tr>
    </table>
</div>

<div id="heating-boost-dialog" title="Set Heating Boost">
    <form>
        <fieldset>
            <label for="heatTime">Boost Time:</label>

            <select name="time" id="heatTime">
                <?php
                $default = 180;
                for ($i = 0; $i <= 360; $i = $i + 15) :
                    ?>

                    <option value="<?php echo $i ?>" <?php if ($i == $default) echo 'selected="selected"' ?> >
                        <?php
                        if ($i > 59) {
                            $decTime = $i/60;
                            $hour = floor($decTime);
                            $min = round(60*($decTime-$hour));
                            echo $hour.'h ';
                            echo sprintf('%02d',$min).'m';
                        } else {
                            echo "0h ".sprintf('%02d',$i)."m";
                        }
                        ?>
                    </option>
                <?php endfor; ?>


                <option value="720" <?php if ($i == $default) echo 'selected="selected"' ?> >
                    12h
                </option>

                <option value="1440" <?php if ($i == $default) echo 'selected="selected"' ?> >
                    24h/1d
                </option>

                <option value="2880" <?php if ($i == $default) echo 'selected="selected"' ?> >
                    48h/2d
                </option>

                <option value="4320" <?php if ($i == $default) echo 'selected="selected"' ?> >
                    72h/3d
                </option>

                <option value="5760" <?php if ($i == $default) echo 'selected="selected"' ?> >
                    96h/4d
                </option>

            </select>
            </br>

            <label for="heatTemp">Boost Temp:</label> <select name="temp" id="heatTemp">
                <?php
                $default = 18;

                for ($i = 0; $i <= 11; $i = $i + 3) :
                    ?>
                    <option value="<?php echo $i ?>" <?php if ($i == $default) echo 'selected="selected"' ?> >
                        <?php echo $i ?>&deg;
                    </option>
                <?php
                endfor;

                for ($i = 12; $i <= 22; $i = $i + 0.5) :
                    ?>
                    <option value="<?php echo $i ?>" <?php if ($i == $default) echo 'selected="selected"' ?> >
                        <?php echo $i ?>&deg;
                    </option>
                <?php
                endfor;

                for ($i = 23; $i <= 26; $i = $i + 1) :
                    ?>
                    <option value="<?php echo $i ?>" <?php if ($i == $default) echo 'selected="selected"' ?> >
                        <?php echo $i ?>&deg;
                    </option>
                <?php
                endfor;

                ?>

            </select>

            </br>
            <label for="heatDelay">Delay Time:</label>

            <select name="delay" id="heatDelay">
                <?php
                $default = 0;
                for ($i = 0; $i <= 360; $i = $i + 15) :
                    ?>

                    <option value="<?php echo $i ?>" <?php if ($i == $default) echo 'selected="selected"' ?> >
                        <?php
                        if ($i > 59) {
                            $decTime = $i/60;
                            $hour = floor($decTime);
                            $min = round(60*($decTime-$hour));
                            echo $hour.'h ';
                            echo sprintf('%02d',$min).'m';
                        } else {
                            echo "0h ".sprintf('%02d',$i)."m";
                        }
                        ?>
                    </option>

                <?php endfor; ?>

            </select>


        </fieldset>
    </form>
</div>

<div id="water-boost-dialog" title="Set Water Boost">
    <form>
        <fieldset>
            <label for="waterTime">Boost Time:</label> <select name="time" id="waterTime">
                <?php
                $default = 60;
                for ($i = 10; $i <= 180; $i = $i + 10) :
                    ?>

                    <option value="<?php echo $i ?>" <?php if ($i == $default) echo 'selected="selected"' ?> >
                        <?php
                        if ($i > 59) {
                            echo ($i/60)." hours";
                        } else {
                            echo $i." minutes";
                        }
                        ?>
                    </option>
                <?php endfor; ?>
            </select>
        </fieldset>
    </form>
</div>
