<div id="navbar">
	<div id="navbarInner">
		<ul>
            <li><a href="<?= $this->url(array('controller' => 'options', 'action' => 'index'),'default',true); ?>">opts</a></li>
            <li><a href="<?= $this->url(array('controller' => 'status', 'action' => 'index'),'default',true); ?>">stat</a></li>
            <li><a href="<?= $this->url(array('controller' => 'history', 'action' => 'index'),'default',true); ?>">hist</a></li>
            <li><a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'),'default',true); ?>">home</a></li>
		</ul>
	</div>
</div>
