<div id="navbar">
	<div id="navbarInner">
		<ul>
		<li><a href="<?= $this->url(array('controller' => 'status', 'action' => 'index'),'default',true); ?>">status</a></li>
		<li><a href="<?= $this->url(array('controller' => 'groups', 'action' => 'index'),'default',true); ?>">groups</a></li>
		<li><a href="<?= $this->url(array('controller' => 'schedules', 'action' => 'index'),'default',true); ?>">sched</a></li>
		<li><a href="<?= $this->url(array('controller' => 'holidays', 'action' => 'index'),'default',true); ?>">hols</a></li>
		<li><a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'),'default',true); ?>">home</a></li>
		</ul>
	</div>
</div>